[package]
name = "zbus_polkit"
version = "5.1.0"
authors = [
	"Marc-André Lureau <marcandre.lureau@redhat.com>",
	"Zeeshan Ali Khan <zeenix@gmail.com>",
]
edition = "2024"
rust-version = "1.87"

description = "PolicyKit binding"
repository = "https://github.com/z-galaxy/zbus_polkit/"
keywords = ["D-Bus", "DBus", "IPC"]
license = "MIT"
categories = ["os::unix-apis"]
readme = "README.md"

[features]
default = ["zbus/async-io", "blocking-api"]
tokio = ["zbus/tokio"]
blocking-api = ["zbus/blocking-api"]

[dependencies]
zbus = { version = "5.0.0", default-features = false }
serde = { version = "1.0.200", features = ["derive"] }
serde_repr = "0.1.19"
enumflags2 = { version = "0.7.9", features = ["serde"] }
static_assertions = "1.1.0"
nix = { version = "0.31.2", features = ["process", "user"] }
systemd = "0.10.1"
libsystemd-sys = "0.9.4"
thiserror = "2.0.18"

[dev-dependencies]
byteorder = "1.5.0"
tokio = { version = "1", features = ["full"] }
rpassword = "7.5.2"
